# Archivo YAML

max_jugadores_por_partida: 4
max_partidas: 5

segundos_duracion_partida: 180

vida_inicial: 5

aceleracion_gravedad: 1

velocidad_arma_infinita: 6
dano_arma_infinita: 1
frames_recarga_arma_infinita: 16

velocidad_arma1: 4
dano_arma1: 1
frames_recarga_arma1: 33

velocidad_arma2: 8
caida_arma2: 1
dano_arma2: 2
frames_recarga_arma2: 66

velocidad_arma3: 10
dano_arma3: 3
frames_recarga_arma3: 132

# probabilidad de los objetos que sueltan los enemigos
# probabilidades. Aumentar un numero aumenta la probabilidad de ese caso
probabilidad_comida: 2
probabilidad_municion: 100
# si la probabilidad anterior salio comida, puede salir uno de estos dos
probabilidad_comida_buena: 1
probabilidad_comida_mala: 1
# si la probabilidad anterior salio muncion, puede salir uno de estos tres
probabilidad_municion_1: 1
probabilidad_municion_2: 100
probabilidad_municion_3: 1

#estadisticas de los enemigos
vida_lagarto: 6
vida_murcielago: 3
vida_esqueleto: 9

dano_lagarto: 1
dano_murcielago: 2
dano_esqueleto: 3

velocidad_lagarto: 2
velocidad_murcielago: 3
velocidad_esqueleto: 1

puntos_lagarto: 250
puntos_murcielago: 500
puntos_esqueleto: 1000

frames_hasta_revivir_lagarto: 200
frames_hasta_revivir_murcielago: 300
frames_hasta_revivir_esqueleto: 600
