#ifndef TIPO_COMANDO_H
#define TIPO_COMANDO_H

enum TipoComando : char {
    NINGUNA,
    CREAR,
    UNIR,
    SALTAR,
    MOVER_IZQ,
    PARAR_MOVER_IZQ,
    MOVER_DER,
    PARAR_MOVER_DER,
    ACTIVAR_DASH,
    DESACTIVAR_DASH,
    DISPARAR_ACCION,
    ACTIVAR_ATAQUE_ESPECIAL,
    ARMA_ANTERIOR,
    ARMA_SIGUIENTE,
    TRUCO1,
    TRUCO2,
    TRUCO3,
    VALIDAR_ESCENARIO,
};

#endif
