#ifndef TIPO_BLOQUE_ESCENARIO_H
#define TIPO_BLOQUE_ESCENARIO_H

enum TipoBloqueEscenario : char {
    PISO,
    PARED,
    DIAGONAL,
    DIAGONAL_INVERTIDO,
    SOPORTE_DIAGONAL,
    SOPORTE_DIAGONAL_INVERTIDO,
    SPAWNPOINT_JUGADOR,
    SPAWNPOINT_ENEMIGO,
    GEMA,
    MONEDA
};
#endif
